### ISSUE TITLE
Allow seat maps with more than 25 seats

### ISSUE THREAD

**Issue by eXpl0it3r** [OmarMahili/SeatchartJS#19]
Some seat maps require more than 25 seats, but currently the limit for both rows and columns is 25. Changing this limit requires a few things to adapt as well:

- The labeling of the seat, can't just use the alphabet, as there are only a limited number of letters in the English alphabet
- The size of each seat needs to be better adjustable, so a larger range can be placed next to each other

**Comment by omahili** [comment]
Hi @eXpl0it3r!

You can change seat labels according to your needs with `options.map.seatName` callback.
Additionally you can change the indexes with `options.map.indexes.rows.name` and `options.map.indexes.columns.name` callbacks. 

Yes, you are right the limit is 25 and it was chosen for convenience: to stay within the limit of the English alphabet letters (26) and due to the seat indexing adopted. With this formula `seatIndex = (totalColumns * seatRow) + seatColumn` the limit of indexable columns is 99.

You can overcome the limit of 25 by removing the check on the parameters in the first lines of code, but then you are stuck with the limit of 99 columns. In fact I'm planning to switch to a simpler and more convenient indexing method which would remove completely this limit. An idea is using objects like `{ r: 10, c:10 }`. 

Regarding the size of each seat I need to figure out how to implement it. It's not ideal but to overcome it now you can customize the style of seats and make them bigger or reduce their inner text size.
A solution to make this dynamic in the future could be using tooltips over a certain size but somehow I'm not convinced. Suggestions are welcome 😄

**Comment by omahili** [comment]
Fixed in #39
