### ISSUE TITLE
 Object doesn't support property or method 'append' in IE11

### ISSUE THREAD

**Issue by Gert-JanPeeters** [OmarMahili/SeatchartJS#24]
There is a minor bug with viewing the seatchart.js in Internet Exployer. I am using IE11 and I get the the following error:

` Object doesn't support property or method 'append'
columnIndexContainer.append(rowIndexContainer);`

For me, this was fixed when changed to

`columnIndexContainer.appendChild(rowIndexContainer);`

If you want, I can open a pull request to fix this issue. But it is the first time I attempt to contribute to a project on Github so please bare with me :)

**Comment by omahili** [comment]
Hi @Gert-JanPeeters, thank you for pointing it out.
Yes that should work fine, the only difference is that `append()` is newer: it supports multiple arguments and appending strings.

Consider that I'm moving the whole codebase to Typescript: you can see the development in the branch feature/typescript. So basically every new change in `develop` needs to be repeated again in that branch since a simple merge wouldn't work.
Said that, feel free to open a PR if you want, otherwise just wait for the changes in that branch to be merged in develop.

**Comment by omahili** [comment]
I just built the typescript project, and it looks like the issues with IE11 go beyond `append()`. I think that a set of polyfills could solve them. I'll go deeper into it and try to find a way to make it work with IE11.

**Comment by Gert-JanPeeters** [comment]
Thanks. Then I'll wait for the changes.

**Comment by omahili** [comment]
[Polyfill.io](https://cdn.polyfill.io/v3/url-builder/) might be useful since it provides an ulr builder for polyfills.
As of today, the polyfills needed to make the typescript version of Seatchart work on IE11 are:

- es5
- Array.prototype.find
- Element.prototype.append
- Element.prototype.remove
- DOMTokenList.forEach

The last one is not available on _polyfill.io_ but it can be found in the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/forEach). I already opened an issue on their repository to hopefull get this polyfill available soon, since `DOMTokenList` and `DOMTokenList.prototype.@@iterator` do not solve the issue.
